import { createReducer } from "@ngrx/store";

export class Post {
    "id": number;
    "title": string;
    "date_published": Date;
    "thumbnail": string;
    "paragraphs": Paragraph[]
}

class Paragraph {
  "paragraph": string;
  "image": string | null
}

export const postsFeatureKey = "posts";

export class PostsState{
  "posts": Post[];
  "error": string;
  "status": string;
}

export const initialState: PostsState = {
  posts: [
    {
      "id": 1,
      "title": "Freelancing on upwork",
      "date_published": new Date(1674723142999),
      "thumbnail": "",
      "paragraphs": [
        {
          "paragraph": "Upwork is a popular platform for freelancers to connect with clients and find work. The platform has a wide range of job categories, from writing and programming to design and customer service. It allows freelancers to create a profile, list their skills, and bid on job listings posted by clients.",
          "image": ""
        },
        {
          "paragraph": "One of the benefits of using Upwork as a freelancer is the ability to work from anywhere and have a flexible schedule. It also allows freelancers to work with clients from all over the world and expand their professional network. Additionally, Upwork offers a variety of tools to help freelancers manage their projects, such as a time tracking feature and a messaging system to communicate with clients.",
          "image": ""
        },
        {
          "paragraph": "One of the downsides of Upwork is the competition for jobs. Since the platform is open to freelancers worldwide, there can be a lot of competition for the same job listings. To stand out, freelancers should have a well-rounded profile, including a detailed description of their skills and experience, as well as a portfolio of their work.",
          "image": ""
        },
        {
          "paragraph": "Another downside of Upwork is the fees they charge. Upwork charges a service fee of 2.75% to 5% of the total amount earned, depending on the freelancer's membership level. This fee can add up and eat into freelancers' earnings, so it's important for freelancers to factor in this cost when bidding on job listings.",
          "image": ""
        },
        {
          "paragraph": "Overall, Upwork can be a great platform for freelancers to find work and expand their professional network. However, it's important for freelancers to be aware of the competition and fees associated with using the platform. To be successful on Upwork, freelancers should have a well-rounded profile, a strong portfolio, and be mindful of the costs associated with using the platform.",
          "image": ""
        },
        {
          "paragraph": "Full disclaimer: I am not the author of this article. It was generated by OpenAI which I find remarkable.",
          "image": ""
        }
      ]
    },
    {
      "id": 2,
      "title": "Learning to code",
      "date_published": new Date(1662224484435),
      "thumbnail": "",
      "paragraphs": [
        {
          "paragraph": "pp1",
          "image": ""
        },
        {
          "paragraph": "pp1",
          "image": ""
        },
        {
          "paragraph": "pp1",
          "image": ""
        },
        {
          "paragraph": "Full disclaimer: I am not the author of this article. It was generated by OpenAI which I find remarkable.",
          "image": ""
        }
      ]
    }
  ],
  error: '',
  status: ''
}

export const PostsReducer = createReducer(
  initialState
)
